/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by injection-gen. DO NOT EDIT.

package client

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	discovery "k8s.io/client-go/discovery"
	dynamic "k8s.io/client-go/dynamic"
	rest "k8s.io/client-go/rest"
	versioned "knative.dev/net-gateway-api/pkg/client/gatewayapi/clientset/versioned"
	typednetworkingv1alpha1 "knative.dev/net-gateway-api/pkg/client/gatewayapi/clientset/versioned/typed/apis/v1alpha1"
	injection "knative.dev/pkg/injection"
	dynamicclient "knative.dev/pkg/injection/clients/dynamicclient"
	logging "knative.dev/pkg/logging"
	v1alpha1 "sigs.k8s.io/gateway-api/apis/v1alpha1"
)

func init() {
	injection.Default.RegisterClient(withClientFromConfig)
	injection.Default.RegisterClientFetcher(func(ctx context.Context) interface{} {
		return Get(ctx)
	})
	injection.Dynamic.RegisterDynamicClient(withClientFromDynamic)
}

// Key is used as the key for associating information with a context.Context.
type Key struct{}

func withClientFromConfig(ctx context.Context, cfg *rest.Config) context.Context {
	return context.WithValue(ctx, Key{}, versioned.NewForConfigOrDie(cfg))
}

func withClientFromDynamic(ctx context.Context) context.Context {
	return context.WithValue(ctx, Key{}, &wrapClient{dyn: dynamicclient.Get(ctx)})
}

// Get extracts the versioned.Interface client from the context.
func Get(ctx context.Context) versioned.Interface {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		if injection.GetConfig(ctx) == nil {
			logging.FromContext(ctx).Panic(
				"Unable to fetch knative.dev/net-gateway-api/pkg/client/gatewayapi/clientset/versioned.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).")
		} else {
			logging.FromContext(ctx).Panic(
				"Unable to fetch knative.dev/net-gateway-api/pkg/client/gatewayapi/clientset/versioned.Interface from context.")
		}
	}
	return untyped.(versioned.Interface)
}

type wrapClient struct {
	dyn dynamic.Interface
}

var _ versioned.Interface = (*wrapClient)(nil)

func (w *wrapClient) Discovery() discovery.DiscoveryInterface {
	panic("Discovery called on dynamic client!")
}

func convert(from interface{}, to runtime.Object) error {
	bs, err := json.Marshal(from)
	if err != nil {
		return fmt.Errorf("Marshal() = %w", err)
	}
	if err := json.Unmarshal(bs, to); err != nil {
		return fmt.Errorf("Unmarshal() = %w", err)
	}
	return nil
}

// NetworkingV1alpha1 retrieves the NetworkingV1alpha1Client
func (w *wrapClient) NetworkingV1alpha1() typednetworkingv1alpha1.NetworkingV1alpha1Interface {
	return &wrapNetworkingV1alpha1{
		dyn: w.dyn,
	}
}

type wrapNetworkingV1alpha1 struct {
	dyn dynamic.Interface
}

func (w *wrapNetworkingV1alpha1) RESTClient() rest.Interface {
	panic("RESTClient called on dynamic client!")
}

func (w *wrapNetworkingV1alpha1) BackendPolicies(namespace string) typednetworkingv1alpha1.BackendPolicyInterface {
	return &wrapNetworkingV1alpha1BackendPolicyImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "backendpolicies",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1BackendPolicyImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.BackendPolicyInterface = (*wrapNetworkingV1alpha1BackendPolicyImpl)(nil)

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Create(ctx context.Context, in *v1alpha1.BackendPolicy, opts v1.CreateOptions) (*v1alpha1.BackendPolicy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "BackendPolicy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BackendPolicy, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BackendPolicyList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicyList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackendPolicy, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Update(ctx context.Context, in *v1alpha1.BackendPolicy, opts v1.UpdateOptions) (*v1alpha1.BackendPolicy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "BackendPolicy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) UpdateStatus(ctx context.Context, in *v1alpha1.BackendPolicy, opts v1.UpdateOptions) (*v1alpha1.BackendPolicy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "BackendPolicy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.BackendPolicy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1BackendPolicyImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) Gateways(namespace string) typednetworkingv1alpha1.GatewayInterface {
	return &wrapNetworkingV1alpha1GatewayImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "gateways",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1GatewayImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.GatewayInterface = (*wrapNetworkingV1alpha1GatewayImpl)(nil)

func (w *wrapNetworkingV1alpha1GatewayImpl) Create(ctx context.Context, in *v1alpha1.Gateway, opts v1.CreateOptions) (*v1alpha1.Gateway, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "Gateway",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.Gateway{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1GatewayImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1GatewayImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Gateway, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.Gateway{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GatewayList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Gateway, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.Gateway{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) Update(ctx context.Context, in *v1alpha1.Gateway, opts v1.UpdateOptions) (*v1alpha1.Gateway, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "Gateway",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.Gateway{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) UpdateStatus(ctx context.Context, in *v1alpha1.Gateway, opts v1.UpdateOptions) (*v1alpha1.Gateway, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "Gateway",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.Gateway{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) GatewayClasses() typednetworkingv1alpha1.GatewayClassInterface {
	return &wrapNetworkingV1alpha1GatewayClassImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "gatewayclasses",
		}),
	}
}

type wrapNetworkingV1alpha1GatewayClassImpl struct {
	dyn dynamic.NamespaceableResourceInterface
}

var _ typednetworkingv1alpha1.GatewayClassInterface = (*wrapNetworkingV1alpha1GatewayClassImpl)(nil)

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Create(ctx context.Context, in *v1alpha1.GatewayClass, opts v1.CreateOptions) (*v1alpha1.GatewayClass, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "GatewayClass",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClass{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GatewayClass, error) {
	uo, err := w.dyn.Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClass{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GatewayClassList, error) {
	uo, err := w.dyn.List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClassList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GatewayClass, err error) {
	uo, err := w.dyn.Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClass{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Update(ctx context.Context, in *v1alpha1.GatewayClass, opts v1.UpdateOptions) (*v1alpha1.GatewayClass, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "GatewayClass",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClass{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) UpdateStatus(ctx context.Context, in *v1alpha1.GatewayClass, opts v1.UpdateOptions) (*v1alpha1.GatewayClass, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "GatewayClass",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.GatewayClass{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1GatewayClassImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) HTTPRoutes(namespace string) typednetworkingv1alpha1.HTTPRouteInterface {
	return &wrapNetworkingV1alpha1HTTPRouteImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "httproutes",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1HTTPRouteImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.HTTPRouteInterface = (*wrapNetworkingV1alpha1HTTPRouteImpl)(nil)

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Create(ctx context.Context, in *v1alpha1.HTTPRoute, opts v1.CreateOptions) (*v1alpha1.HTTPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "HTTPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HTTPRoute, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HTTPRouteList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRouteList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HTTPRoute, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Update(ctx context.Context, in *v1alpha1.HTTPRoute, opts v1.UpdateOptions) (*v1alpha1.HTTPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "HTTPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) UpdateStatus(ctx context.Context, in *v1alpha1.HTTPRoute, opts v1.UpdateOptions) (*v1alpha1.HTTPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "HTTPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.HTTPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1HTTPRouteImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) TCPRoutes(namespace string) typednetworkingv1alpha1.TCPRouteInterface {
	return &wrapNetworkingV1alpha1TCPRouteImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "tcproutes",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1TCPRouteImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.TCPRouteInterface = (*wrapNetworkingV1alpha1TCPRouteImpl)(nil)

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Create(ctx context.Context, in *v1alpha1.TCPRoute, opts v1.CreateOptions) (*v1alpha1.TCPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TCPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TCPRoute, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TCPRouteList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRouteList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TCPRoute, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Update(ctx context.Context, in *v1alpha1.TCPRoute, opts v1.UpdateOptions) (*v1alpha1.TCPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TCPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) UpdateStatus(ctx context.Context, in *v1alpha1.TCPRoute, opts v1.UpdateOptions) (*v1alpha1.TCPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TCPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TCPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TCPRouteImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) TLSRoutes(namespace string) typednetworkingv1alpha1.TLSRouteInterface {
	return &wrapNetworkingV1alpha1TLSRouteImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "tlsroutes",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1TLSRouteImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.TLSRouteInterface = (*wrapNetworkingV1alpha1TLSRouteImpl)(nil)

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Create(ctx context.Context, in *v1alpha1.TLSRoute, opts v1.CreateOptions) (*v1alpha1.TLSRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TLSRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TLSRoute, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TLSRouteList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRouteList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TLSRoute, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Update(ctx context.Context, in *v1alpha1.TLSRoute, opts v1.UpdateOptions) (*v1alpha1.TLSRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TLSRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) UpdateStatus(ctx context.Context, in *v1alpha1.TLSRoute, opts v1.UpdateOptions) (*v1alpha1.TLSRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "TLSRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.TLSRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1TLSRouteImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapNetworkingV1alpha1) UDPRoutes(namespace string) typednetworkingv1alpha1.UDPRouteInterface {
	return &wrapNetworkingV1alpha1UDPRouteImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "networking.x-k8s.io",
			Version:  "v1alpha1",
			Resource: "udproutes",
		}),

		namespace: namespace,
	}
}

type wrapNetworkingV1alpha1UDPRouteImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typednetworkingv1alpha1.UDPRouteInterface = (*wrapNetworkingV1alpha1UDPRouteImpl)(nil)

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Create(ctx context.Context, in *v1alpha1.UDPRoute, opts v1.CreateOptions) (*v1alpha1.UDPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "UDPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UDPRoute, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UDPRouteList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRouteList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UDPRoute, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Update(ctx context.Context, in *v1alpha1.UDPRoute, opts v1.UpdateOptions) (*v1alpha1.UDPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "UDPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) UpdateStatus(ctx context.Context, in *v1alpha1.UDPRoute, opts v1.UpdateOptions) (*v1alpha1.UDPRoute, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "networking.x-k8s.io",
		Version: "v1alpha1",
		Kind:    "UDPRoute",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1alpha1.UDPRoute{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapNetworkingV1alpha1UDPRouteImpl) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}
